"""Palette officielle de la charte graphique MIA (2026) — module partagé."""

DEEP_BLUE, BLEU_QUANTIQUE, BLEU_LUMEN = "#163458", "#98A8C6", "#C2D4EF"
ROUGE_LOVELACE, TERRA, AURIA = "#994845", "#AE6557", "#F2B2A5"
MATIERE_GRISE, DATA_BLOOM, NEURA_VERDE = "#C0C0BE", "#E5EAA8", "#F1F4D0"
WHITE = "#FFFFFF"
# teintes de profondeur du Deep Blue (fenêtres / panneaux)
DEEP_BLUE_2, DEEP_BLUE_3 = "#112B4B", "#0E2440"

CHARTE_COLORS = {DEEP_BLUE, BLEU_QUANTIQUE, BLEU_LUMEN, ROUGE_LOVELACE, TERRA, AURIA,
                 MATIERE_GRISE, DATA_BLOOM, NEURA_VERDE, WHITE, DEEP_BLUE_2, DEEP_BLUE_3}
